apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  #acts like a sidegar container
  - image: almalinux
    name: almalinux
    command: [ "sleep", "100" ]
    volumeMounts:
    - mountPath: /mnt/nginx-logs
      name: nginx-logs
      readOnly: true

  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi
