#https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/static-provisioning/manifests/pv.yaml
# manually created the volume  below is volum id
#vol-0664bf166b9e2c7b0
# Copyright 2024 The Kubernetes Authors.
# we need to install the CSI drivers from the official repos
#https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md
#kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.59"
# once we install the driver the kubernetes cluster will speak with ebs-csi-drivers
#attach AmazonCBSCSIDriverPolicy to the workernod IAM  role to  provide authorization
# after the we need to create.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-provisioning
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0664bf166b9e2c7b0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static-provisioning # this the PV name
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/htm
  #
  nodeSelector:
    topology.kubernetes.io/zone: "us-east-1d"

  volumes:
  - name: html-data
    persistentVolumeClaim:
      claimName: ebs-claim
  #commands to to check the pv, pvc
  #kubectl apply -f 03-ebs-static-provising.yaml
  #kubectl get pv
  #kubectl get pvc

  #describe pvc es-claim
  #  kubectl describe pv
  #   kubectl apply -f 03-ebs-static-provising.yaml

  #kubectl api-resources | grep pv
  #kubectl api-resources
  #kubecl delete pod nginx
  #kubectl delete pvc ebs-claim
  #kubectl delete pv ebs-static-provisioning

  #I need to continue April 8th session from timing 1:25:08 

