apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-ebs-claim-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: roboshop-ebs-sc #referene of 04-ebs-storage-class.yaml strorage class name
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/htm
  #
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c # "us-east-1d"

  volumes:
  - name: html-data
    persistentVolumeClaim:
      claimName: roboshop-ebs-claim-dynamic
