apiVersion: v1
kind: Pod
metadata:
  name: labels-demo
  #namespace: roboshop
  #Labels are used to provide metadata to objects. They act a selectors to identify a set of objects.
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx:latest

#ImagePullBackOff/ErrorImagePull-> When the node is not able to pull the image from the registry.
#This can happen due to various reasons such as incorrect image name, missing image, or issues with the registry.
#CrashLoopBackOff -> When the container is not able to start successfully and keeps crashing.
