apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:latest
    envFrom:
    - configMapRef:
        name: app-config # configmap name referenced in the 08-configmap.yaml file 
