apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:latest
    envFrom:
    - secretRef:
        name: app-secret # secret name referenced in the 10-secret.yaml file
