#if we want to communicat with two pods we need to create a service.
#ip address of the pods are not static so we need to create a service to communicate with the pods. 
#service will have a static ip address and it will forward the traffic to the pods.
#and loading balance the traffic between the pods.
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    #by default the service type is ClusterIP. It exposes the service on a cluster-internal IP.
    #label are used as a selectors to select the pods which are running nginx.
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    #services are of four types:
    #1. ClusterIP: It is the default type of service. It exposes the service on a cluster-internal IP. 
    # It is only accessible within the cluster.
    #2. NodePort: It exposes the service on each node's IP at a static port. It is accessible from outside the cluster 
    #using <NodeIP>:<NodePort>.
    #3. LoadBalancer: It exposes the service externally using a cloud provider's load balancer. 
    #It is accessible from outside the cluster using the load balancer's IP address.
    #4. ExternalName: It maps the service to the contents of the externalName field.
