#NodePort service exposes the service on each node's IP at a static port. 
#It is accessible from outside the cluster using <NodeIP>:<NodePort>.
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  #NodePort service exposes the service on each node's IP at a static port. 
  #It is accessible from outside the cluster using <NodeIP>:<NodePort>.
  #clusterIP is a subset of NodePort.
  #port range for NodePort is 30000-32767.
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30005
