#ReplicaSet is a controller which ensures that a specified number of pod replicas are running at any given time.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  #these are required labels for replicaset to identify the pods it manages. 
  #These labels should match the labels defined in the pod template.
  labels:
    project: roboshop
    component: frontend
    environment: dev
    purpose: replicaset-demo
spec:
  replicas: 3 #number of pod replicas to be maintained
  selector:
    #using these labels the replicaset will identify the pods it manages.
    matchLabels:
      project: roboshop
      component: frontend
      environment: dev
      purpose: replicaset-demo
  #This is the pod template which defines the pod specification. 
  #The replicaset will create pods based on this template.
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        environment: dev
        purpose: replicaset-demo
    spec:
      containers:
      - name: nginx
        image: nginx:9
